### ISSUE TITLE
requests is missing from setup.py

### ISSUE THREAD

**Issue by tcr3dr** [diydrones/dronekit-python#193]
```
======================================================================
ERROR: Failure: ImportError (No module named requests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/Library/Python/2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/Library/Python/2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/Users/travis/build/diydrones/dronekit-python/tests/cloud_client_test.py", line 3, in <module>
    from droneapi.lib.CloudClient import *
  File "/Users/travis/build/diydrones/dronekit-python/droneapi/lib/CloudClient.py", line 1, in <module>
    import requests
ImportError: No module named requests
```

**Comment by tcr3dr** [comment]
Fixed by https://github.com/diydrones/dronekit-python/commit/e7241d50cb034bdeb0f02b6843f4f6f0cdf75acc
