### ISSUE TITLE
Implementation missing for battery_0_soc and battery_0_volt

### ISSUE THREAD

**Issue by hamishwillee** [diydrones/dronekit-python#71]
There is no implementation for battery_0_soc and battery_0_volt. Please provide implementation and information about what parameters these map to on ardupilot (basically I need to know their "meaning" and possible values and units - so for example "Remaining capacity of the first battery in X units"

It is possible for a UAV to have multiple batteries, and two are specified in the [parameters](http://copter.ardupilot.com/wiki/configuration/arducopter-parameters/#batt__parameters). This implies that there should actually be multiple values for these, or a way to index them.

I verified the lack of these parameters by inspection and testing. To test, I added the following lines to [small_demo.py](https://github.com/diydrones/dronekit-python/blob/master/example/small_demo/small_demo.py#L32):

```
print "battery_0_soc: %s" % v.battery_0_soc
print "battery_0_volt: %s" % v.battery_0_volt
```

And got the exception:

```
Exception in APIThread-2: 'MPVehicle' object has no attribute 'battery_0_soc'
Traceback (most recent call last):
  File "C:\Users\hamis_000\Downloads\WinPython-64bit-2.7.6.4\python-2.7.6.amd64\lib\site-packages\droneapi\module\api.py", line 321, in run
    self.fn()
  File "C:\Users\hamis_000\Downloads\WinPython-64bit-2.7.6.4\python-2.7.6.amd64\lib\site-packages\droneapi\module\api.py", line 592, in <lambda>
    APIThread(self, lambda: execfile(args[1], g), args[1])
  File "small_demo.py", line 32, in <module>
    print "battery_0_soc: %s" % v.battery_0_soc
AttributeError: 'MPVehicle' object has no attribute 'battery_0_soc'
```

**Comment by hamishwillee** [comment]
Closing as this is dealt with by #101 and #102.
